// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gpt

// Injectors from wire.go:

func InitApp() (*App, error) {
	args, err := ProvideArgs()
	if err != nil {
		return nil, err
	}
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	app := &App{
		Args:   args,
		Config: config,
	}
	return app, nil
}
