// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gpt

import (
	"github.com/hayeah/goo"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/sqlite3"
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	args, err := ProvideArgs()
	if err != nil {
		return nil, err
	}
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	client := ProvideOpenAI(config)
	gooConfig := ProvideGooConfig(config)
	shutdownContext, err := goo.ProvideShutdownContext()
	if err != nil {
		return nil, err
	}
	logger, err := goo.ProvideZeroLogger(gooConfig, shutdownContext)
	if err != nil {
		return nil, err
	}
	db, err := goo.ProvideSQLX(gooConfig, shutdownContext, logger)
	if err != nil {
		return nil, err
	}
	jsondb := ProvideJSONDB(db)
	assistantManager := &AssistantManager{
		OAI:    client,
		JSONDB: jsondb,
	}
	threadManager := &ThreadManager{
		OAI:    client,
		JSONDB: jsondb,
	}
	openAIConfig := ProvideOpenAIConfig(config)
	openAIClientV2 := ProvideOpenAIV2(config)
	threadRunner := &ThreadRunner{
		OpenAIConfig: openAIConfig,
		OAI:          client,
		OAIV2:        openAIClientV2,
		AM:           assistantManager,
	}
	migrate, err := goo.ProvideMigrate(gooConfig)
	if err != nil {
		return nil, err
	}
	app := &App{
		Args:         args,
		Config:       config,
		OAI:          client,
		AM:           assistantManager,
		TM:           threadManager,
		ThreadRunner: threadRunner,
		Migrate:      migrate,
	}
	return app, nil
}
